name: Daily Dashboard Update

on:
  schedule:
    # Runs every day at midnight UTC
    - cron: '0 0 * * *'
  workflow_dispatch: # Allows manual triggering

permissions:
  contents: write
  actions: read

jobs:
  update-daily:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Generate daily chart
      run: |
        python3 flex_gantt.py pipeline.xlsx --daily --dashboard
        
    - name: Configure Git
      run: |
        git config --global user.name 'Dashboard Automation'
        git config --global user.email 'automation@marquisdashboard.com'
        
    - name: Commit and push changes
      run: |
        git add slides/
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "🤖 Auto-update: Daily dashboard - $(date +'%A, %B %d, %Y')"
          git push origin main
        fi
        
    - name: Log completion
      run: |
        echo "✅ Daily update completed successfully"
        echo "🌐 Live at: https://www.marquisdashboard.com"
        echo "📍 Generated today's events chart" 