name: Monthly Dashboard Update

on:
  schedule:
    # Runs on the 1st of every month at 3:45 AM UTC (off-peak) = 10:45 PM CDT previous day
    - cron: '45 3 1 * *'
  workflow_dispatch: # Allows manual triggering

permissions:
  contents: write
  actions: read

jobs:
  update-monthly:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Cache Python dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Generate rolling window charts
      run: |
        python3 flex_gantt.py pipeline.xlsx --rolling-window --dashboard
        
    - name: Generate calendar view
      run: |
        python3 flex_gantt.py pipeline.xlsx --calendar --dashboard
        
    - name: Configure Git
      run: |
        git config --global user.name 'Dashboard Automation'
        git config --global user.email 'automation@marquisdashboard.com'
        
    - name: Commit and push changes
      run: |
        git add slides/
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "🤖 Auto-update: Monthly dashboard - $(date +'%B %Y') 4-month rolling window + calendar"
          git push origin main || {
            echo "Push failed, retrying in 30 seconds..."
            sleep 30
            git push origin main
          }
        fi
        
    - name: Log completion
      run: |
        echo "✅ Monthly update completed successfully"
        echo "🌐 Live at: https://www.marquisdashboard.com"
        echo "📅 Generated new calendar view"
        echo "📊 Updated 4-month rolling window" 